#!/bin/bash

# Facebook Notifications-cli v0.1 04-01-2014
# This script created by vagrale13 (vagrale@gmail.com)

# Translator:
Your Name Here

# Language:
Your Language NAME here

## TRANSLATION YOUR LANGUAGE NAME, ON YOUR LANGUAGE ##
Your translation language Name, on your language here.



 #====================================#
#          script translations         #
 #====================================#


## DO NOT TRANSLATE 'xterm' and 'setup.sh' JUST COPY-PASTE IT ##
# You must install 'xterm' to use this script
# Install 'xterm' package and run again 'setup.sh'
Your translation here...
...and here.

## DO NOT TRANSLATE 'fbcmd' JUST COPY-PASTE IT ##
# Press [Enter] to open the 'fbcmd' web page...
Your translation here...

## DO NOT TRANSLATE 'vagrale13' and 'Facebook' JUST COPY-PASTE IT ##
# This script created from 'vagrale13'
# to show information from your Facebook ID account.
Your translation here...
...and here.

## DO NOT TRANSLATE 'fbcmd' JUST COPY-PASTE IT ##
# Uses 'fbcmd' tool. More info about 'fbcmd'
# you can see here http://fbcmd.dtompkins.com/introduction
Your translation here...
...and here.

## DO NOT TRANSLATE 'GPL license Version 3 (GPLv3)' JUST COPY-PASTE IT ##
# This script is under GPL license Version 3 (GPLv3)
Your translation here...

## DO NOT TRANSLATE 'GPL' JUST COPY-PASTE IT ##
# You can read about GPL licence
# with command: cat /usr/share/common-licenses/GPL-3
# or in web page http://www.gnu.org/licenses/gpl.txt
Your translation here...
...here...
...and here.

# For any problems that arise on your pc or illegal use of this script
# the responsibility lies solely with the person who use it.
Your translation here...
...and here.

# If you do not agree with the above, please stop the process (Ctrl+C).
# Press [Enter] to continue install...
Your translation here...
...and here.

# Install completed.
Your translation here...

## DO NOT TRANSLATE 'fcbntf-cli' & 'fcbntf-cli.tar.gz' JUST COPY-PASTE IT ##
# You can delete folder 'fcbntf-cli'
# and archive 'fcbntf-cli.tar.gz' no longer needed.
Your translation here...
...and here.

## DO NOT TRANSLATE 'Facebook Notifications-cli' JUST COPY-PASTE IT ##
# You can run 'Facebook Notifications-cli' from menu.
Your translation here...

# Information about
Your translation here...

# Page
Your translation here...

## DO NOT TRANSLATE NUMBER '1' JUST COPY-PASTE IT ##
# You have 1 new message
Your translation here...

## DO NOT TRANSLATE NUMBER '10' JUST COPY-PASTE IT ##
# You have 10 new messages
Your translation here...

## DO NOT TRANSLATE NUMBER '1' JUST COPY-PASTE IT ##
# You have 1 new poke
Your translation here...

## DO NOT TRANSLATE NUMBER '10' JUST COPY-PASTE IT ##
# You have 10 new pokes
Your translation here...

## DO NOT TRANSLATE NUMBER '1' JUST COPY-PASTE IT ##
# You have 1 new notification
Your translation here...

## DO NOT TRANSLATE NUMBER '10' JUST COPY-PASTE IT ##
# You have 10 new notifications
Your translation here...

## DO NOT TRANSLATE NUMBER '1' JUST COPY-PASTE IT ##
# You have 1 friend request
Your translation here...

## DO NOT TRANSLATE NUMBER '10' JUST COPY-PASTE IT ##
# You have 10 friend requests
Your translation here...

## DO NOT TRANSLATE NUMBER '1' JUST COPY-PASTE IT ##
# There is 1 friend who has birthday today
Your translation here...

## DO NOT TRANSLATE NUMBER '10' JUST COPY-PASTE IT ##
# There are 10 friends who have birthdays today
Your translation here...

## DO NOT TRANSLATE NUMBER '10' JUST COPY-PASTE IT ##
# There are 10 friends Online and 10 friends idle
Your translation here...

# Friends who have birthdays today
Your translation here...

# Friends Online
Your translation here...



 #============================================#
#    End of FcbNtf-cli script translations     #
 #============================================#



# Thank you for your help and support!
# Send it to my e-mail: vagrale@gmail.com
# and i put all new changes into it. :)


